### ISSUE TITLE
Invoke-IcingaCheckHyperVSnapshot - Exception calling "WarnOutOfRange" with "1" argument(s): "Cannot convert value "B" to type "System.Decimal". Error: "Input string was not in a correct format.""

### ISSUE THREAD

**Issue by K0nne** [Icinga/icinga-powershell-hyperv#67]
Hello!

On some of our HyperV hosts the check `Invoke-IcingaCheckHyperVSnapshot` has problems while parsing the results. 
Those machines seems to behave different than the majority. It happens in our qs and prod stage.

**Output:**
```
Plugin-Ausgabe
[UNKNOWN] Icinga Exception: Exception calling "WarnOutOfRange" with "1" argument(s): "Cannot convert value "B" to type  
 "System.Decimal". Error: "Input string was not in a correct format.""

CheckCommand: Invoke-IcingaCheckHyperVSnapshot Arguments: System.Collections.Hashtable StackTrace: at Invoke- 
 IcingaCheckHyperVSnapshot, C:\Program Files\WindowsPowerShell\Modules\icinga-powershell-hyperv\compiled\icinga-powershell- 
 hyperv.ifw_compilation.psm1: line 623 at Exit-IcingaExecutePlugin, C:\Program Files\WindowsPowerShell\Modules\icinga-powershell- 
 framework\cache\framework_cache.psm1: line 26525 at , : line 1
```

Line 623:
![image](https://github.com/Icinga/icinga-powershell-hyperv/assets/34264690/63538139-cc41-451a-8cd1-4061eb582fad)

**Comment by K0nne** [comment]
This is the plugin execution:

`icinga {Invoke-IcingaCheckHyperVSnapshot -CreationTimeCritical 1209600s -TotalSnapshotSizeWarning 30% -TotalSnapshotSizeCritical 40% -Verbosity 2 -AvoidEmptyCheck}`

**Important finding:**
The error appears only if the arguments  -TotalSnapshotSizeWarning or -TotalSnapshotSizeCritical are used. Otherwise everything works fine.

**Comment by LordHepipud** [comment]
Could you please test the linked PR? This should resolve the problem.

**Comment by K0nne** [comment]
With the PR the error message differs slightly, but its still the same. Do I have to change something within the framework?

```
Exception calling "WarnOutOfRange" with "1" argument(s): "Cannot convert value "B" to type "System.Decimal". Error: "Input string was not in a correct format.""
At C:\Program Files\WindowsPowerShell\Modules\icinga-powershell-hyperv\compiled\icinga-powershell-hyperv.ifw_compilation.psm1:624 char:17
+                 $SnapshotMainCheck.AddCheck(
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : ScriptMethodRuntimeException

[OK] VM Snapshots: 5 Ok
```

**Comment by K0nne** [comment]
Unfortunately I did everything right:

Sniplet from overview:
```
framework    1.11.0
hyperv       1.3.0
```

check execution:
```
PS C:\Program Files\WindowsPowerShell\Modules\icinga-powershell-framework> icinga {Invoke-IcingaCheckHyperVSnapshot -TotalSnapshotSizeWarning 30% -TotalSnapshotSizeCritical 40%} -DeveloperMode -RebuildCache
Exception calling "WarnOutOfRange" with "1" argument(s): "Cannot convert value "B" to type "System.Decimal". Error: "Input string was not in a correct format.""
At C:\Program Files\WindowsPowerShell\Modules\icinga-powershell-hyperv\compiled\icinga-powershell-hyperv.ifw_compilation.psm1:624 char:17
+                 $SnapshotMainCheck.AddCheck(
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : ScriptMethodRuntimeException

[OK] VM Snapshots: 5 Ok
```

**Comment by K0nne** [comment]
The affected snapshot is from a vm without scsi controller and disk:

![image](https://github.com/Icinga/icinga-powershell-hyperv/assets/34264690/8a8e2f45-1b27-47e5-9269-5d05223f8b7c)
